


//------------------- 安卓模板 模块 -------------------

;(function () {

    //模板数据layout 最外层
    document.writeln('<!-- 模板数据ViewController -->');
    document.writeln('		<script type=\"text/x-tmpl\" id=\"tmpl-android-xml\">');
    document.writeln('<?xml version=\"1.0\" encoding=\"utf-8\"?>');
    document.writeln('<RelativeLayout');
    document.writeln('    xmlns:android=\"http://schemas.android.com/apk/res/android\"');
    document.writeln('    xmlns:app=\"http://schemas.android.com/apk/res-auto\"');
    document.writeln('    xmlns:tools=\"http://schemas.android.com/tools\"');
    document.writeln('    android:layout_width=\"match_parent\"');
    document.writeln('    android:layout_height=\"match_parent\"');
    document.writeln('    >');
    document.writeln('		      {% if (o.root.views) { %}');
    document.writeln('		      {% var templateViewsValue = document.getElementById(\"tmpl-android-views\").innerHTML;var map = {};map[\"root\"] = o.root.views; var ret = tmpl(templateViewsValue, map); %}');
    document.writeln('		      {% if(ret) { %}');
    document.writeln('		      {%=ret%}');
    document.writeln('		      {% } %}');
    document.writeln('		      {% } %}');
    document.writeln('</RelativeLayout>');
    document.writeln('		    </script>');

    //模板数据View
    document.writeln('<!-- 模板数据View -->');
    document.writeln('<script type=\"text/x-tmpl\" id=\"tmpl-android-views\">');
    document.writeln('');
    document.writeln('    		{% for (var i=0; i<o.root.length; i++) { %}');
    document.writeln('    		{% var tempView = o.root[i]; %}');
    document.writeln('');
    document.writeln('    		{% if (tempView.viewType == \"textView\") { %}');
    document.writeln('                <TextView');
    document.writeln('                    {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('                    android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('                    android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('                    {% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    {% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    {% if (tempView.text) { %}android:text=\"{%=tempView.text %}\"{% } %}');
    document.writeln('                    {% if (tempView.align) { %}android:textAlignment=\"{%=tempView.align %}\"{% } %}');
    document.writeln('                    android:textSize=\"{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}dp\"');
    document.writeln('                    {% if (tempView.font_family) { %}android:fontFamily=\"{%=tempView.font_family %}\"{% } %}');
    document.writeln('                    {% if (tempView.textColor) { %}android:textColor=\"{%=tempView.textColor %}\"{% } %}');
    document.writeln('                    {% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    >');
    document.writeln('                </TextView>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"switch\") { %}');
    document.writeln('    				<Switch');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('        				android:layout_width=\"wrap_content\"');
    document.writeln('        				android:layout_height=\"wrap_content\">');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</Switch>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"scrollView\") { %}');
    document.writeln('    				<ScrollView');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('        				android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('                    	{% if (tempView.views) { %}');
    document.writeln('    		            {% var templateViewsValue = document.getElementById(\"tmpl-android-views\").innerHTML;var map = {};map[\"root\"] = tempView.views; var ret = tmpl(templateViewsValue, map); %}');
    document.writeln('    		            {% if(ret) { %}');
    document.writeln('    		            {%=ret%}');
    document.writeln('    		            {% } %}');
    document.writeln('    		            {% } %}');
    document.writeln('   					</ScrollView>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"editText\") { %}');
    document.writeln('					<EditText');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('						android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('						{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('						{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('						{% if (tempView.text) { %}android:text=\"{%=tempView.text %}\"{% } %}');
    document.writeln('						{% if (tempView.align) { %}android:textAlignment=\"{%=tempView.align %}\"{% } %}');
    document.writeln('						android:textSize=\"{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}dp\"');
    document.writeln('						{% if (tempView.font_family) { %}android:fontFamily=\"{%=tempView.font_family %}\"{% } %}');
    document.writeln('						{% if (tempView.textColor) { %}android:textColor=\"{%=tempView.textColor %}\"{% } %}');
    document.writeln('						{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } else { %}android:background=\"@null\"{% } %}');
    document.writeln('						>');
    document.writeln('					</EditText>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"imageView\") { %}');
    document.writeln('    		    	<ImageView');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				android:scaleType=\"fitXY\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	{% if (tempView.image) { %}android:src=\"@drawable/{%=tempView.image %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</ImageView>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"button\") { %}');
    document.writeln('    				<Button');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.text) { %}android:text=\"{%=tempView.text %}\"{% } %}');
    document.writeln('						{% if (tempView.align) { %}android:textAlignment=\"{%=tempView.align %}\"{% } %}');
    document.writeln('						android:textSize=\"{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}dp\"');
    document.writeln('						{% if (tempView.font_family) { %}android:fontFamily=\"{%=tempView.font_family %}\"{% } %}');
    document.writeln('						{% if (tempView.textColor) { %}android:textColor=\"{%=tempView.textColor %}\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</Button>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"progressBar\") { %}');
    document.writeln('    				<ProgressBar');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</ProgressBar>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"recyclerView\") { %}');
    document.writeln('    				<androidx.recyclerview.widget.RecyclerView');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	android:orientation=\"vertical\"');
    document.writeln('                    	app:layoutManager=\"androidx.recyclerview.widget.LinearLayoutManager\"');
    document.writeln('                    	>');
    document.writeln('   					</androidx.recyclerview.widget.RecyclerView>');
    document.writeln('                />');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"datePicker\") { %}');
    document.writeln('    				<DatePicker');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</DatePicker>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"webView\") { %}');
    document.writeln('    				<WebView');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</WebView>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"seekBar\") { %}');
    document.writeln('    				<SeekBar');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('   					</SeekBar>');
    document.writeln('    		{% } %}');
    document.writeln('    		{% if (tempView.viewType == \"relativeLayout\") { %}');
    document.writeln('    				<RelativeLayout');
    document.writeln('                      {% if (tempView.defineName) { %}android:id=\"@+id/{%=tempView.defineName %}\"{% } %}');
    document.writeln('    		    		android:layout_width=\"{%=tempView.width %}dp\"');
    document.writeln('        				android:layout_height=\"{%=tempView.height %}dp\"');
    document.writeln('        				{% if (parseFloat(tempView.x) > 0) { %}android:layout_marginLeft=\"{%=tempView.x %}dp\"{% } %}');
    document.writeln('                    	{% if (parseFloat(tempView.y) > 0) { %}android:layout_marginTop=\"{%=tempView.y %}dp\"{% } %}');
    document.writeln('                    	{% if (tempView.bgColor) { %}android:background=\"{%=tempView.bgColor %}\"{% } %}');
    document.writeln('                    	>');
    document.writeln('                    	{% if (tempView.views) { %}');
    document.writeln('    		            {% var templateViewsValue = document.getElementById(\"tmpl-android-views\").innerHTML;var map = {};map[\"root\"] = tempView.views; var ret = tmpl(templateViewsValue, map); %}');
    document.writeln('    		            {% if(ret) { %}');
    document.writeln('    		            {%=ret%}');
    document.writeln('    		            {% } %}');
    document.writeln('    		            {% } %}');
    document.writeln('   					</RelativeLayout>');
    document.writeln('    		{% } %}');
    document.writeln('');
    document.writeln('    		{% } %}');
    document.writeln('    			</script>');

})(this);

//------------------- 安卓模板 模块 -------------------



