


//------------------- 自定义模板 模块 -------------------

;(function () {

    document.writeln("<script type=\'text/x-tmpl\' id=\'tmpl-define-xml\'>");
    document.writeln("    {控件集合");
    document.writeln("     宽度=\'match_parent\'");
    document.writeln("     高度=\'match_parent\'");
    document.writeln("     {% if (o.root.views) { %}");
    document.writeln("     {% var templateViewsValue = get_template();var map = {};map[\'root\'] = o.root.views; var ret = tmpl(templateViewsValue, map); %}");
    document.writeln("     {% if(ret) { %}");
    document.writeln("     {%=ret%}");
    document.writeln("     {% } %}");
    document.writeln("     {% } %}");
    document.writeln("    控件集合}");
    document.writeln("</script>");
    document.writeln("");
    document.writeln("");
    document.writeln("<script type=\'text/x-tmpl\' id=\'tmpl-define-views\'>");
    document.writeln("     {% for (var i=0; i<o.root.length; i++) { %}");
    document.writeln("     {% var tempView = o.root[i]; %}");
    document.writeln("     {% if (tempView.viewType == \'textView\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.text) { %}文本内容=\'{%=tempView.text %}\'{% } %}");
    document.writeln("     {% if (tempView.align) { %}文本对齐方式=\'{%=tempView.align %}\'{% } %}");
    document.writeln("     字体大小=\'{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}\'");
    document.writeln("     {% if (tempView.font_family) { %}字体系列=\'{%=tempView.font_family %}\'{% } %}");
    document.writeln("     {% if (tempView.textColor) { %}字体颜色=\'{%=tempView.textColor %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'scrollView\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     {% if (tempView.views) { %}");
    document.writeln("     {% var templateViewsValue = get_template();var map = {};map[\'root\'] = tempView.views; var ret = tmpl(templateViewsValue, map); %}");
    document.writeln("     {% if(ret) { %}");
    document.writeln("     {%=ret%}");
    document.writeln("     {% } %}");
    document.writeln("     {% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'editText\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.text) { %}文本内容=\'{%=tempView.text %}\'{% } %}");
    document.writeln("     {% if (tempView.align) { %}文本对齐方式=\'{%=tempView.align %}\'{% } %}");
    document.writeln("     字体大小=\'{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}\'");
    document.writeln("     {% if (tempView.font_family) { %}字体系列=\'{%=tempView.font_family %}\'{% } %}");
    document.writeln("     {% if (tempView.textColor) { %}字体颜色=\'{%=tempView.textColor %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } else { %}背景颜色=\'@null\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("	{% if (tempView.viewType == \'switch\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'wrap_content\'");
    document.writeln("     高度=\'wrap_content\'>");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'imageView\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     {% if (tempView.image) { %}图片=\'{%=tempView.image %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'button\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.text) { %}文本内容=\'{%=tempView.text %}\'{% } %}");
    document.writeln("     {% if (tempView.align) { %}文本对齐方式=\'{%=tempView.align %}\'{% } %}");
    document.writeln("     字体大小=\'{% if (tempView.font) { %}{%=tempView.font %}{% } else { %}14{% } %}\'");
    document.writeln("     {% if (tempView.font_family) { %}字体系列=\'{%=tempView.font_family %}\'{% } %}");
    document.writeln("     {% if (tempView.textColor) { %}字体颜色=\'{%=tempView.textColor %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'progressBar\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'listView\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     />");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'datePicker\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'webView\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'seekBar\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% if (tempView.viewType == \'view\') { %}");
    document.writeln("     {//控件类型开始:{%=tempView.viewType %}");
    document.writeln("     {% if (tempView.defineName) { %}命名=\'{%=tempView.defineName %}\'{% } %}");
    document.writeln("     宽度=\'{%=tempView.width %}\'");
    document.writeln("     高度=\'{%=tempView.height %}\'");
    document.writeln("     {% if (parseFloat(tempView.x) > 0) { %}左边距=\'{%=tempView.x %}\'{% } %}");
    document.writeln("     {% if (parseFloat(tempView.y) > 0) { %}上边距=\'{%=tempView.y %}\'{% } %}");
    document.writeln("     {% if (tempView.bgColor) { %}背景颜色=\'{%=tempView.bgColor %}\'{% } %}");
    document.writeln("     {% if (tempView.views) { %}");
    document.writeln("     {% var templateViewsValue = get_template();var map = {};map[\'root\'] = tempView.views; var ret = tmpl(templateViewsValue, map); %}");
    document.writeln("     {% if(ret) { %}");
    document.writeln("     {%=ret%}");
    document.writeln("     {% } %}");
    document.writeln("     {% } %}");
    document.writeln("     }//控件类型结束");
    document.writeln("     {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("     {% } %}");
    document.writeln("</script>");

})(this);

//------------------- 自定义模板 模块 -------------------



