


//------------------- flutter模板 模块 -------------------

;(function () {

    // <!-- 模板数据Flutter 由于我不会Flutter,所以模板写了个大概,模板很容易理解,可自行修改 -->

    document.writeln("<script type=\'text/x-tmpl\' id=\'tmpl-flutter-xml\'>");
    document.writeln("    Positioned(");
    document.writeln("        left: 0,");
    document.writeln("        top: 0,");
    document.writeln("        child: Container(");
    document.writeln("              width: {%=o.root.width %},");
    document.writeln("              height: {%=o.root.height %},");
    document.writeln("              {% if (o.root.bgColor) { %}color: Color({%=o.root.bgColor %}),{% } %}");
    document.writeln("              {% if (o.root.views) { %}");
    document.writeln("                  {% var templateViewsValue = document.getElementById(\'tmpl-flutter-views\').innerHTML;var map = {};map[\'root\'] = o.root.views; var ret = tmpl(templateViewsValue, map); %}");
    document.writeln("                {% if(ret) { %}");
    document.writeln("                child: Stack(");
    document.writeln("                  fit: StackFit.passthrough,");
    document.writeln("                  children: <Widget>[");
    document.writeln("                  {%=ret%}");
    document.writeln("                  ]");
    document.writeln("                  ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } %}");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("</script>");
    document.writeln("");
    document.writeln("");
    document.writeln("<script type=\'text/x-tmpl\' id=\'tmpl-flutter-views\'>");
    document.writeln("");
    document.writeln("{% for (var i=0; i<o.root.length; i++) { %}");
    document.writeln("    {% var viewInfo = o.root[i]; %}");
    document.writeln("");
    document.writeln("");
    document.writeln("    {% if (viewInfo.viewType == \'text\') { %}");
    document.writeln("    Positioned(");
    document.writeln("        left: {%=viewInfo.x %},");
    document.writeln("        top: {%=viewInfo.y %},");
    document.writeln("        child: Container(");
    document.writeln("            {% if (viewInfo.borderColor || viewInfo.border_width || viewInfo.border_radius) { %}");
    document.writeln("                decoration: BoxDecoration(");
    document.writeln("                {% if (viewInfo.border_radius) { %}borderRadius: const BorderRadius.all(const Radius.circular({%=viewInfo.border_radius %})),{% } %}");
    document.writeln("                {% if (viewInfo.borderColor || viewInfo.border_width) { %}");
    document.writeln("                    borderSide: BorderSide(");
    document.writeln("                        {% if (viewInfo.border_width) { %} width: {%=viewInfo.border_width %},{% } %}");
    document.writeln("                        {% if (viewInfo.borderColor) { %} color: Color({%=viewInfo.borderColor %}),{% } %}");
    document.writeln("                    ),");
    document.writeln("                ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } else { %}");
    document.writeln("            {% if (viewInfo.bgColor) { %}color: Color({%=viewInfo.bgColor %}),{% } %}");
    document.writeln("            {% } %}");
    document.writeln("              width: {%=viewInfo.width %},");
    document.writeln("              height: {%=viewInfo.height %},");
    document.writeln("              child: Text(");
    document.writeln("                 {% if (viewInfo.text) { %} \'{%=viewInfo.text %}\' {% } %},");
    document.writeln("                 textAlign: TextAlign.{%=viewInfo.align %},");
    document.writeln("                 overflow: TextOverflow.ellipsis,");
    document.writeln("                 style: TextStyle(");
    document.writeln("                    {% if (viewInfo.text) { %} fontFamily: \'{%=viewInfo.font_family %}\', {% } %}");
    document.writeln("                    fontSize: {% if (viewInfo.font) { %}{%=viewInfo.font %}{% } else { %}14{% } %},");
    document.writeln("                    color: Color({%=viewInfo.textColor %}),");
    document.writeln("                 ),");
    document.writeln("            )");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("    {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("    {% if (viewInfo.viewType == \'textField\') { %}");
    document.writeln("    Positioned(");
    document.writeln("        left: {%=viewInfo.x %},");
    document.writeln("        top: {%=viewInfo.y %},");
    document.writeln("        child: Container(");
    document.writeln("            {% if (viewInfo.borderColor || viewInfo.border_width || viewInfo.border_radius) { %}");
    document.writeln("                decoration: BoxDecoration(");
    document.writeln("                {% if (viewInfo.border_radius) { %}borderRadius: const BorderRadius.all(const Radius.circular({%=viewInfo.border_radius %})),{% } %}");
    document.writeln("                {% if (viewInfo.borderColor || viewInfo.border_width) { %}");
    document.writeln("                    borderSide: BorderSide(");
    document.writeln("                        {% if (viewInfo.border_width) { %} width: {%=viewInfo.border_width %},{% } %}");
    document.writeln("                        {% if (viewInfo.borderColor) { %} color: Color({%=viewInfo.borderColor %}),{% } %}");
    document.writeln("                    ),");
    document.writeln("                ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } else { %}");
    document.writeln("            {% if (viewInfo.bgColor) { %}color: Color({%=viewInfo.bgColor %}),{% } %}");
    document.writeln("            {% } %}");
    document.writeln("              width: {%=viewInfo.width %},");
    document.writeln("              height: {%=viewInfo.height %},");
    document.writeln("              child: TextField(");
    document.writeln("                  textAlign: TextAlign.start,");
    document.writeln("                  decoration: InputDecoration(");
    document.writeln("                      {% if (viewInfo.text) { %} hintText: \'{%=viewInfo.text %}\', {% } %}");
    document.writeln("                    hintStyle: TextStyle(color: Colors.grey),");
    document.writeln("                    hintMaxLines: 1");
    document.writeln("                  ),");
    document.writeln("                  style: TextStyle(");
    document.writeln("                    {% if (viewInfo.text) { %} fontFamily: \'{%=viewInfo.font_family %}\', {% } %}");
    document.writeln("                    fontSize: {% if (viewInfo.font) { %}{%=viewInfo.font %}{% } else { %}14{% } %},");
    document.writeln("                    color: Color({%=viewInfo.textColor %}),");
    document.writeln("                 ),");
    document.writeln("            )");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("    {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("    {% if (viewInfo.viewType == \'image\') { %}");
    document.writeln("    Positioned(");
    document.writeln("        left: {%=viewInfo.x %},");
    document.writeln("        top: {%=viewInfo.y %},");
    document.writeln("        child: Container(");
    document.writeln("            {% if (viewInfo.borderColor || viewInfo.border_width || viewInfo.border_radius) { %}");
    document.writeln("                decoration: BoxDecoration(");
    document.writeln("                {% if (viewInfo.border_radius) { %}borderRadius: const BorderRadius.all(const Radius.circular({%=viewInfo.border_radius %})),{% } %}");
    document.writeln("                {% if (viewInfo.borderColor || viewInfo.border_width) { %}");
    document.writeln("                    borderSide: BorderSide(");
    document.writeln("                        {% if (viewInfo.border_width) { %} width: {%=viewInfo.border_width %},{% } %}");
    document.writeln("                        {% if (viewInfo.borderColor) { %} color: Color({%=viewInfo.borderColor %}),{% } %}");
    document.writeln("                    ),");
    document.writeln("                ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } else { %}");
    document.writeln("            {% if (viewInfo.bgColor) { %}color: Color({%=viewInfo.bgColor %}),{% } %}");
    document.writeln("            {% } %}");
    document.writeln("              width: {%=viewInfo.width %},");
    document.writeln("              height: {%=viewInfo.height %},");
    document.writeln("              child: Image.network(");
    document.writeln("                  {% if (viewInfo.image) { %}\'{%=viewInfo.image %}\',{% } %}");
    document.writeln("                  fit: BoxFit.fill");
    document.writeln("            )");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("    {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("    {% if (viewInfo.viewType == \'button\') { %}");
    document.writeln("    Positioned(");
    document.writeln("        left: {%=viewInfo.x %},");
    document.writeln("        top: {%=viewInfo.y %},");
    document.writeln("        child: Container(");
    document.writeln("            {% if (viewInfo.borderColor || viewInfo.border_width || viewInfo.border_radius) { %}");
    document.writeln("                decoration: BoxDecoration(");
    document.writeln("                {% if (viewInfo.border_radius) { %}borderRadius: const BorderRadius.all(const Radius.circular({%=viewInfo.border_radius %})),{% } %}");
    document.writeln("                {% if (viewInfo.borderColor || viewInfo.border_width) { %}");
    document.writeln("                    borderSide: BorderSide(");
    document.writeln("                        {% if (viewInfo.border_width) { %} width: {%=viewInfo.border_width %},{% } %}");
    document.writeln("                        {% if (viewInfo.borderColor) { %} color: Color({%=viewInfo.borderColor %}),{% } %}");
    document.writeln("                    ),");
    document.writeln("                ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } else { %}");
    document.writeln("            {% if (viewInfo.bgColor) { %}color: Color({%=viewInfo.bgColor %}),{% } %}");
    document.writeln("            {% } %}");
    document.writeln("              width: {%=viewInfo.width %},");
    document.writeln("              height: {%=viewInfo.height %},");
    document.writeln("              child: SizedBox(");
    document.writeln("                child: FlatButton(");
    document.writeln("                    padding: EdgeInsets.symmetric(horizontal: 0),");
    document.writeln("                    child: Text(");
    document.writeln("                        {% if (viewInfo.text) { %} \'{%=viewInfo.text %}\' {% } %},");
    document.writeln("                        textAlign: TextAlign.{%=viewInfo.align %},");
    document.writeln("                        overflow: TextOverflow.ellipsis,");
    document.writeln("                        style: TextStyle(");
    document.writeln("                            {% if (viewInfo.text) { %} fontFamily: \'{%=viewInfo.font_family %}\', {% } %}");
    document.writeln("                            fontSize: {% if (viewInfo.font) { %}{%=viewInfo.font %}{% } else { %}14{% } %},");
    document.writeln("                            color: Color({%=viewInfo.textColor %}),");
    document.writeln("                        ),");
    document.writeln("                    ),");
    document.writeln("                    onPressed: (){");
    document.writeln("                        print(\'点击事件\');");
    document.writeln("                    },");
    document.writeln("                )");
    document.writeln("              )");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("    {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("    {% if (viewInfo.viewType == \'container\') { %}");
    document.writeln("    Positioned(");
    document.writeln("        left: {%=viewInfo.x %},");
    document.writeln("        top: {%=viewInfo.y %},");
    document.writeln("        child: Container(");
    document.writeln("            {% if (viewInfo.borderColor || viewInfo.border_width || viewInfo.border_radius) { %}");
    document.writeln("                decoration: BoxDecoration(");
    document.writeln("                {% if (viewInfo.border_radius) { %}borderRadius: const BorderRadius.all(const Radius.circular({%=viewInfo.border_radius %})),{% } %}");
    document.writeln("                {% if (viewInfo.borderColor || viewInfo.border_width) { %}");
    document.writeln("                    borderSide: BorderSide(");
    document.writeln("                        {% if (viewInfo.border_width) { %} width: {%=viewInfo.border_width %},{% } %}");
    document.writeln("                        {% if (viewInfo.borderColor) { %} color: Color({%=viewInfo.borderColor %}),{% } %}");
    document.writeln("                    ),");
    document.writeln("                ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } else { %}");
    document.writeln("            {% if (viewInfo.bgColor) { %}color: Color({%=viewInfo.bgColor %}),{% } %}");
    document.writeln("            {% } %}");
    document.writeln("              width: {%=viewInfo.width %},");
    document.writeln("              height: {%=viewInfo.height %},");
    document.writeln("              {% if (viewInfo.views) { %}");
    document.writeln("                {% var templateViewsValue = document.getElementById(\'tmpl-flutter-views\').innerHTML;var map = {};map[\'root\'] = viewInfo.views; var ret = tmpl(templateViewsValue, map); %}");
    document.writeln("                {% if(ret) { %}");
    document.writeln("                child: Stack(");
    document.writeln("                  fit: StackFit.passthrough,");
    document.writeln("                  children: <Widget>[");
    document.writeln("                  {%=ret%}");
    document.writeln("                  ]");
    document.writeln("                  ),");
    document.writeln("                {% } %}");
    document.writeln("            {% } %}");
    document.writeln("          )");
    document.writeln("    ),");
    document.writeln("    {% } %}");
    document.writeln("");
    document.writeln("");
    document.writeln("{% } %}");
    document.writeln("</script>");
    document.writeln("");

})(this);

//------------------- flutter模板 模块 -------------------
